update /comments /checklists /checklist_items
hieutt99/aidudu pull request #68
Opened 2021-12-03 15:09 UTC by palizu

2021-12-05 01:35 UTC, minhdq99hp requested changes
serializer.py: tại sao lại override hàm init? t chưa hiểu lắm

views.py 423: Partial update là Patch rồi nhé, ko override lại hàm put

2021-12-05 06:44 UTC, palizu commented
T test thì nếu dùng put data phải có đủ các fields thì nó mới cho update, ko thì bị 400
Nếu để patch thì có cần sửa verb trong api ko

2021-12-06 02:58 UTC, minhdq99hp commented
Trong hàm partial_update nó set partial = true rồi, ở postman ô gọi patch thay vì put, ko cần gửi lên tất cả các field

2021-12-07 15:28 UTC, minhdq99hp requested changes
Ok

2021-12-07 15:28 UTC, minhdq99hp approved these changes
Ok

2021-12-07 15:28 UTC, merged