Sonpt
hieutt99/aidudu pull request #73
Opened 2021-12-04 21:11 UTC by P3nt3st3r123

2021-12-04 21:12 UTC, P3nt3st3r123 commented
cập nhật bản test cho develop branch

2021-12-05 01:39 UTC, minhdq99hp requested changes
Sơn đi merge branch của Văn đấy à, sao commit mấy cái giống thế?

Đợi Văn merge trc rồi ô merge sau nhé

2021-12-05 03:08 UTC, P3nt3st3r123 reviewed
Bản của này chỉ thêm phần test thôi. Chứ không thêm tính năng gì đâu nhé

2021-12-08 06:52 UTC, minhdq99hp approved these changes
Ok

2021-12-08 06:52 UTC, merged